### ISSUE TITLE
magic home v2.3 issues

### ISSUE THREAD

**Issue by tarbax** [arendst/Sonoff-Tasmota#1353]
my device is an RGBW with IR magic ligic home light version 2.3
configured to magic home
GPIO4 ->IRrecv
GPIO13 Led1i -> PWM4
i also did the ''command 15 1''

colors are not correct and i have no rgb control on the main webpage of tasmota only brightness
commands:
color 1 (gives no light   dedicated white are off)
color 2 (green light   dedicated white are off)
color 3 (red light   dedicated white are off)
color 4 (dimmed grey light   dedicated white are off)
color 12 ( green/yellow light   dedicated white are off)
color  000000ff ( blue light   dedicated white are off)
color FFFFFFFF (rgb are all on white   dedicated white are off)

how to fix this and how to add this to home assistant ?

**Comment by arendst** [comment]
- Tasmota does not provide RGB light control on web page.
- Your Magic light uses different PWM channels than supported by Tasmota Magic Light module. This is expected as every day the Chinese provide new GPIO configurations. No problem as you can easily provide the GPIO configuration yourself using the Wemos D1 module.

So verify your results against the current Magic Light module config parameters in sonoff_template.h , select the wemos module and enter the correct PWM channel information.

In Tasmota PWM1 is Red, PWM2 is Green, PWM3 is Blue and PWM4 is White when an RGBW device is connected.

As an example your Green channel seems to be OK so select for GPIO5 option 34 PWM2. As ``color 3`` should be Blue but your receive Red you know that GPIO12 must be option 33 PWM1. Experiement with the other two PWMs.

Success.

As for Home Assistant...

**Comment by tarbax** [comment]
Thanks arendst!
my Colors are correct now but now i have an other issue
i need to set these extra that i dont heve/need
RRGGBBCCWW  CC for color temp but dont need how to disable this
17:03:36 CMD: color 000000FF
17:03:36 MQT: stat/magichome/RESULT = {"Color":"FFFFFFFFFF"}

how to fix this ?

**Comment by arendst** [comment]
It seems you configured one PWM channel too much. Verify you only have 4 PWM channels configured.

**Comment by tarbax** [comment]
Thanks Arendst for the fast reply! 
everything is now working

**Comment by robotdad** [comment]
@tarbax this is what I have for the home assistant configuration. I'm seeing some oddities with the RGB values, but monitoring the messages that is on the home assistant side.

In this example the Living room light is a Sonoff B1, the other is an AiLight.
```
light:
  - platform: mqtt
    name: 'Living room lamp'
    state_topic: "stat/lr_lamp/POWER"
    command_topic: "cmnd/lr_lamp/POWER"
    rgb_state_topic: "stat/lr_lamp/COLOR"
    rgb_command_topic: "cmnd/lr_lamp/COLOR"
    rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
    brightness_state_topic: "stat/lr_lamp/DIMMER"
    brightness_value_template: "{{ value_json.brightness }}"
    brightness_command_topic: "cmnd/lr_lamp/DIMMER"
    brightness_scale: 100
    color_temp_command_topic: "cmnd/lr_lamp/CT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: 'Family room lamp'
    state_topic: "stat/fr_lamp/POWER"
    command_topic: "cmnd/fr_lamp/POWER"
    brightness_state_topic: "stat/fr_lamp/DIMMER"
    brightness_command_topic: "cmnd/fr_lamp/DIMMER"
    brightness_value_template: "{{ value_json.brightness }}"
    brightness_scale: 100
    rgb_state_topic: "stat/fr_lamp/COLOR"
    rgb_command_topic: "cmnd/fr_lamp/COLOR"
    rgb_command_template: "{{ '%02x%02x%02x00' | format(red, green, blue) }}"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
```
