### ISSUE TITLE
MQTT status update 

### ISSUE THREAD

**Issue by rajkedda** [arendst/Sonoff-Tasmota#1603]
Hi
  I have flashed the latest version of the Tasmota onto my Sonoff Basic and using it on HomeAssistant.  How do I send get status update of my sonoff basic and update it on HomeAssistant.  Here is my config for sonoff as light:
- platform: mqtt
  name: "Sonoff Living Room"
  state_topic: "stat/sonoffdev1/POWER"
  command_topic: "cmnd/sonoffdev1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

and in configuration.yaml file for the recorder:
  db_url: mysql://userid:password@localhost/homeassistant?charset=utf8

When I use the HomeAssistant UI, everything works & maintains it fine.  But loses the status after reboot of Raspberry Pi or HomeAssistant.  

Any ideas on how to fix it?

**Comment by pascalsaul** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/1497 (similair)

I'm facing the same issues...

A possible fix can be to enable retain but personally I don't like that option either. Had some sync issues with that option also. I think it is a good idea to implement this feature.

**Comment by gajotnt** [comment]
Working great this way in my setup:
https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant

```
switch:
  - platform: mqtt
    name: "Sonoff power"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    availability_topic: "tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
```

**Comment by pascalsaul** [comment]
Yes, that's with retain what I was saying above ;)

I personally really don't like this option when you've a split brain situation. It sounds as a 'cool' funtion but when you're using it for complex situation it can cause unwanted situations. 

If a bulb is switched in your bedroom through your domotica and the power is retained = bulb on
Now an WiFi/MQTT/HA crash occurs = bulb is still on
I'm going to bed and switching the bulb off through manual control = bulb off
Your HA still thinks the bulb is on (so a sync issue) = bulb off
The WiFi/MQTT/HA service is fully restored = bulb on!
I'm getting awake because the bulb turned on by retain ;) = bulb off

Just a simple situation... that's way I don't want to use retain ;)

**Comment by bensuffolk** [comment]
I have an automation rule that request the status of the device when home assistant starts. The standard configuration for the state topic on the light picks up the reply and updates the state.

Here is an example that queries the status of 3 x T1 switches, just extend it as needed for other switches / lamps etc.

```
- action:
  - data:
      topic: tasmota/cmnd/t1/office/POWER
    service: mqtt.publish
  - data:
      topic: tasmota/cmnd/t1/conservatory/POWER1
    service: mqtt.publish
  - data:
      topic: tasmota/cmnd/t1/conservatory/POWER2
    service: mqtt.publish
  alias: Query Status on startup
  trigger:
  - event: start
    platform: homeassistant

```
