### ISSUE TITLE
sonf of touch  connect bug?

### ISSUE THREAD

**Issue by vMeph** [arendst/Sonoff-Tasmota#1707]
ok i got the sonoff touch working with homeassistant and retain states with the PowerRetain command
so if i restart homeassistant it will get the states of lights from before
now the problems is if you reboot host hassio(HA), then the sonoff cant reconect with mqtt HA, with out restart himself.
if you restart sonoff then it will get the states of lights from before..
the question is why cant sonoff reconect with the host with out restart??
is this a bug?

**Comment by ascillato** [comment]
Hi,

Is not a bug. It is a config problem on Home Assistant (Hass.io). I had the same.

I put the following configuration on Home Assistant and worked no matter which device you restart.

on _configuration.yaml:_

```
# switch
light:
    - platform: mqtt
      name: "NodeMCU Test"
      state_topic: "stat/sonoff/POWER"
      command_topic: "cmnd/sonoff/POWER"
      availability_topic: "tele/sonoff/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      retain: false
```
