### ISSUE TITLE
Ping vs. indicator.connected

### ISSUE THREAD

**Issue by daniel-lo** [arendst/Sonoff-Tasmota#3858]
I have 2 Sonoff 4ch-Pro-R2 devices which I monitor via a ping. What I notice is the following: Quite frequently the devices are not reachable via ping. The outage time is mostly 60/61 seconds (or double .. 122). And even though the pings fail "indicator.connected" stays true.

My assumption is that the devices will operate even though pings fail but nevertheless it might be good to look into this from the Tasmota perpective.

I use blockly scripts in ioBroker. Tasomota is 6.2.1 (happend with the former one too).
Beware .. I am no dev.

**Comment by Jason2866** [comment]
Please fill out issue template. Without no help is possible. `Status 0` is mandantory

**Comment by daniel-lo** [comment]
![oje](https://user-images.githubusercontent.com/4311558/45875992-9ad38700-bd99-11e8-9e3a-091179b48006.png)

**Comment by ascillato** [comment]
Hi,

Tasmota is a MQTT device, you can use the LWT to see if it is online or not.

**Comment by daniel-lo** [comment]
Sorry .. I don't know what LWT is. Isn't that the indicator.connected state I see in the sonoff adapter on iobroker?

**Comment by ascillato** [comment]
LWT is the online/offline indicator in the MQTT protocol. If you have configured all the parameters as explained in the wiki, you will have the online/offline in your MQTT Broker.

**Comment by Jason2866** [comment]
Yes, but seeing is device online or not is the second step...
Why does the device goes offline?!  For that we need `status 0` output.
We can track down (hopefully) the reason for going offline

**Comment by ascillato** [comment]
I don't know how to configure IOBroker. I use HomeAssistant and the config there is like:

```yaml
switch:
  - platform: mqtt
    name: "Sonoff power"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    availability_topic: "tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
```

so, there you see the `availability_topic `that is watching the LWT
