### ISSUE TITLE
Sonoff POW R2, is it possible to change energy values when switch is toggled?

### ISSUE THREAD

**Issue by Klagio** [arendst/Sonoff-Tasmota#4059]
Have the below configuration in Home Assistant. All works fine, but the energy (voltage, etc..) are not updated correctly.
For example when I turn the switch OFF all the values should be updated immediately (Voltage to zero, and so on, while the voltage stays at 220 for long time before updating)

I hope I made myself clear

```
switch:
  - platform: mqtt
    name: "Oven power plug"
    state_topic: "stat/oven/POWER"
    command_topic: "cmnd/oven/POWER"
    availability_topic: "tele/oven/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
sensor:
  - platform: mqtt
    name: Oven Current
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: 'amps'
  - platform: mqtt
    name: Oven Power
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: 'watts'
  - platform: mqtt
    name: Oven Voltage
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: 'volts'
  - platform: mqtt
    name: Total energy consumed
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: 'kWh'
  - platform: mqtt
    name: Yesterday energy consumed
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: 'kWh'
  - platform: mqtt
    name: Today energy consumed
    state_topic: "tele/oven/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: 'kWh'
```
