### ISSUE TITLE
Tuya Dimmer - need help

### ISSUE THREAD

**Issue by h4nc** [arendst/Sonoff-Tasmota#4543]
Hi, 

I followed these instructions to set up my new tuya dimmer:

https://github.com/arendst/Sonoff-Tasmota/wiki/Tuya-Dimmer

I have two issues:

1) The dimmer will be mounted in a bedroom. Is there away to turn off the led's when the dimmer is off?

2) after setting up gpio13 to Rx and gpio15 to tx the device doesn't swith on off when I press the button on it. 
Before it worked, but the dimming buttons did not. 
I selectet the device ID SetOption34 2.
Will this always be "2" or is it an ID of the device itself? Where can I find it?

**Comment by Jason2866** [comment]
Since there is not "the One" Tuya Dimmer nobody cant help without knowing which type you have

**Comment by h4nc** [comment]
You are right, I'm sorry. 

I have the EU model. I also noticed that the layout of my pcb is a little different. The esp is faced the opposite as the picture showed it the documentation. 

![img_7657-2](https://user-images.githubusercontent.com/25117255/49576279-0f53a600-f945-11e8-931d-a637cf991a9c.jpeg)

**Comment by Jason2866** [comment]
@chaosmaster  Can you help? I have no Tuya device (yet)....

**Comment by chaosmaster** [comment]
@h4nc
>     The dimmer will be mounted in a bedroom. Is there away to turn off the led's when the dimmer is off?

Sorry, that's not possible, the LEDs are controlled by the MCU and can only switch between red and blue.
Only the wifi-led (green) LED is controlled by Tasmota.

>     after setting up gpio13 to Rx and gpio15 to tx the device doesn't swith on off when I press the button on it.
This dimmer uses GPIO1 as TX and GPIO3 as RX (the default for "Tuya Dimmer").

>     I selectet the device ID SetOption34 2.
>     Will this always be "2" or is it an ID of the device itself? Where can I find it?
Everything else should be detected automatically in the current development branch.
Otherwise `SetOption34 2` is correct for this device.
The ID depends on the type of Tuya-device and currently there are devices using _2_ or _3_

**Comment by h4nc** [comment]
@chaosmaster 
Thanks for the fast reply. 

> Sorry, that's not possible, the LEDs are controlled by the MCU and can only switch between red and blue.

Is there a line I can cut to disable this three leds that are not managed by tasmota. 
If there is one line to cut, maybe its possible to connect it to the esp, so that it can be controlled by tasmota? Which pin would you recommend? 

So I have it configured like this now (see picture), but the dimmer-buttons don't work. 
<img width="426" alt="bildschirmfoto 2018-12-06 um 13 46 06" src="https://user-images.githubusercontent.com/25117255/49584994-577ec280-f95d-11e8-8d8b-1b064eafed1d.png">
What else could be wrong?

**Comment by h4nc** [comment]
Every led has 4 pins. GND, BLUE, RED and?

It does seem like there is one line I could cut to trigger all blue and another to trigger als red lights.
I still want to use it in my bedroom, but the the leds lightning the whole room in blue in not an option.

How would you to it? Desolder the led's? Cut the lines to the leds?
I could also only cut the blue ones.
Best way for my still would be to be able to use them in tasmota by connecting them to the esp.

Any ideas are welcome!

**Comment by Jason2866** [comment]
- The easiest mod would be cut trace(s)
- For connecting to the ESP (it seems GPIO 12-16 are free)
   you have to add a transistor. GPIO from ESP doesnt deliver enough current to connect it direct.
   The function of the LEDs could be done...

**Comment by ascillato2** [comment]
Great to know, that now the dimmer is working for you.

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by h4nc** [comment]
I marked the Pins of the Power Switch in this picture.

As I would expect a two color led needs 3 pins. So why are there 4 pins per led?

I think a will cut the traces, but first I need to now what the traces are for.

![49586903-c01c6e00-f962-11e8-8924-5fd099fc5193](https://user-images.githubusercontent.com/25117255/49588358-ca406b80-f966-11e8-9ed9-7142583ef2a7.jpg)

**Comment by chaosmaster** [comment]
@h4nc 
You can check [this post](https://github.com/arendst/Sonoff-Tasmota/issues/469#issuecomment-399006536).
It describes what is connected where.
Although the LEDs aren't directly connected to the MCU, they are connected via the CR302-chip.
They are switched between blue and red by pulling the GPIO HIGH or LOW.
To disable them the GPIO can be configured as input.
You can also check out my custom MCU-firmware for this device, to disable the LEDs.
But be warned it isn't completely stable and I haven't had time to look further into it.

I suppose the have 4 pins since, they are all in fact RGB LEDs, although I believe only the top LED has green wired.

Here you can find my custom MCU-firmware:
https://github.com/chaosmaster/tuya_mcu

**Comment by h4nc** [comment]
I still have one open question. I don't want to open a new issue for that.

Why do we have to connect NRST to GND for flashing the device? What does NRST stand for?

**Comment by chaosmaster** [comment]
@h4nc 
NRST is the reset-pin for the MCU it's part of the MCUs programming-interface.
It needs to be pulled LOW during flashing the ESP, because the MCU is connected to the ESPs UART.

**Comment by TommyChausson** [comment]
@h4nc I've got a few question about the EU model, i manage to flash it with the last Tasmota firmware. It work when piloting it by button, by mqtt, by tasmota interface but when i use the switch (toggle or up/down button) no informations are sent by mqtt ? Is there a specific configuration in "Module parameters" interface ? Actually i have : 
- GPIO0 - Button 1
- GPIO1 - Tuya Tx
- GPIO3 - Tuya Rx
- GPI14 -  Led1
 
Thank's

**Comment by TommyChausson** [comment]
@h4nc  Yes, VERY strange, when it boot it send MQTT infos (state etc...), That prove that MQTT info sending is working, only when i touch a button nothing is sent ! What's your tasmota version ?

**Comment by kajmaj** [comment]
I have Tuya Dimmer with  6.4.1(release-sensors), 2.3.0/1.5.3.
Everything works well but after restart (change configuration) it everytime went ON.
PowerOnState is 0

In hassio config retain: false
Is there anything possible to do with it?

**Comment by h4nc** [comment]
Maybe adding this code to your automation.yaml could help, this will call the current state of all your sonoff. You could also change the topic to your tuya dimmer to only call its state.

```
- alias: 'Sonoff - State after Restart'
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  action:
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER
```

**Comment by kajmaj** [comment]
I already have this automation:
```
  - alias: "power_state_on_ha_start_up"
    initial_state: "on"
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/Power3"
        payload: "" 
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power4"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power"
        payload: ""
```
In the case of Tuya it does not have any influence.

And this tuya config:

```
light:
- platform: mqtt
  name: "bedroom"
  state_topic: "stat/bedroom_dim/POWER"
  command_topic: "cmnd/bedroom_dim/POWER"
  availability_topic: "tele/bedroom_dim/LWT"
  brightness_state_topic: "stat/bedroom_dim/RESULT"
  brightness_command_topic: "cmnd/bedroom_dim/Dimmer"
  brightness_scale: 100
  brightness_value_template: >
    {% if value_json.Dimmer is defined %}
      {{ value_json.Dimmer }}
    {% else %}
        {{ state_attr('light.bedroom_dim','brightness') / 255 * 100 }}
    {% endif %}
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
```

**Comment by h4nc** [comment]
Try:

```
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/STATE
```

**Comment by kajmaj** [comment]
response of Tuya Dimmer for STATE: 
`stat/bedroom_dim/RESULT = {"Time":"2019-02-19T18:35:15","Uptime":"0T08:27:51","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Dimmer":53,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"HXXNET","BSSId":"F4:F8:6D:9B:94:A2","Channel":6,"RSSI":60}}`

**Comment by h4nc** [comment]
I use state to get an update of the DIMMER value.

So this too did not help you with your problem, right?

**Comment by kajmaj** [comment]
Well, after first restart not. After restart it is OK. It seems to help
Will see during a day or two.
Thank you

**Comment by kajmaj** [comment]
Everything is back, Tuya dimmer powers on after every reboot.
With mqtt disabled it is OK, with mqtt enabled it is back.
On Tuya,  6.4.1.16(8cb33b8-sensors), 2_5_0/3.0.0-dev(c0f7b44)
PowerRetain OFF
```
19:06:21 CMD: powerretain
19:06:21 MQT: stat/dimmer_1/RESULT = {"PowerRetain":"OFF"}
```
On Hassio config:
`retain: false`
In addition each Hassio reboot:
```
    action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power"
```
