### ISSUE TITLE
Tasmota threw error in HASS on MQTT RGB light turning off

### ISSUE THREAD

**Issue by pszafer** [arendst/Sonoff-Tasmota#4602]
So when MQTT light is turned off it throwing an error in HASS if RGB/state topic are the same.
I thought that it is a bug in HASS so made PR https://github.com/home-assistant/home-assistant/pull/19193, but @emontnemery said that it has been already fixed.

Do you mean that it is fix by this issue? https://github.com/arendst/Sonoff-Tasmota/issues/4358

```
- platform: mqtt
  name: "LED light"
  command_topic: "cmnd/led/POWER"
  state_topic: "stat/led/RESULT"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/led/LWT"
  brightness_command_topic: "cmnd/led/Dimmer"
  brightness_state_topic: "stat/led/RESULT"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/led/CT"
  color_temp_state_topic: "stat/led/RESULT"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/led/Color2"
  rgb_state_topic: "stat/led/RESULT"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/led/Scheme"
  effect_state_topic: "stat/led/RESULT"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
```
