### ISSUE TITLE
How to set SetOption59 1 before compilation?

### ISSUE THREAD

**Issue by lichtamberg** [arendst/Sonoff-Tasmota#4885]
Hi,

the last 2 days I spent time figuring out why my Sonoff Basic Switch only goes online, but not offline or vice versa (at first it worked when I compiled the firmware by myself - but then after some changes and using user_config_override.h it stopped somehow 🤷‍♂️  )...

Then I stumbled upon https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant-%E2%80%90-Manual-Config#configure-switches and finally I made it work again by entering 

```
SetOption59 1
```

in the web console of my switch.

Is there any way to enable this option in the config, before compilation - so I dont have to enter it manually via the web interface?  

I searched for ```SetOption59``` in the sourcecode, but couldn't find any mention (unlike SetOption18 f.e.)?

Thank you!

**Comment by andrethomas** [comment]
You can't set it as a define but it is stored in 

`Settings.SysBitfield3.hass_tele_on_power`

So you could add it to void SettingsDefaultSet2(void) in settings.ino to do

`Settings.SysBitfield3.hass_tele_on_power = 1;`

I would guess...

**Comment by mjoshd** [comment]
Or you cold set it up using the original method... here's an example.

```yaml
# New method (must enter "SetOption59 1" in the console)
- platform: mqtt
  name: "Test Sonoff"
  state_topic: "tele/test_sonoff/STATE"
  value_template: "{{ value_json.POWER }}"
  availability_topic: "tele/test_sonoff/LWT"
  command_topic: "cmnd/test_sonoff/POWER"
  payload_not_available: "Offline"
  payload_available: "Online"
  payload_off: "OFF"
  payload_on: "ON"
  retain: false
  qos: 1
  
# Original method (continues to work with v6.4)
- platform: mqtt
  name: "Test Sonoff"
  state_topic: "stat/test_sonoff/POWER"
  command_topic: "cmnd/test_sonoff/POWER"
  availability_topic: "tele/test_sonoff/LWT"
  payload_not_available: "Offline"
  payload_available: "Online"
  payload_off: "OFF"
  payload_on: "ON"
  retain: false
  qos: 1
```
