### ISSUE TITLE
Wofea WiFi Switch Smart Garage Door Opener support (Tuya)

### ISSUE THREAD

**Issue by riogrande75** [arendst/Sonoff-Tasmota#6319]
I bought some smart garage door openers at AE: [https://aliexpress.com/item/32997953761.html](url)
![SmartGarageDoorOpener](https://user-images.githubusercontent.com/28924474/63995779-ffdf4300-caf9-11e9-9d99-87f38c3ac7fd.jpg)

After opening it, I saw that it is a tuya device based on a TYWE2S module and a STM8S0003F3 mcu.
Off course I flashed it with latest tasmota firmware and begun investigations.
![SmartGarage](https://user-images.githubusercontent.com/28924474/63995845-374def80-cafa-11e9-8e43-3d47c65e69f2.jpg)
![ModuleParameters](https://user-images.githubusercontent.com/28924474/63995874-4af95600-cafa-11e9-88d0-e0602075d41b.jpg)
MCU obviously controls 3 tuya ID's (DpID).
When pressing the button on the device, the relay switches for 2 secs (close contact for garage door controller). Here the log:
`00:00:18 TYA: RX Packet: "55aa03070005010100010011"`
`00:00:18 TYA: RX Device-1 --> MCU State: Off Current State:On`
`00:00:18 SRC: Switch`
`00:00:18 RSL: stat/GarageRechts/RESULT = {"POWER":"OFF"}`
`00:00:18 RSL: stat/GarageRechts/POWER = OFF`
`00:00:19 CFG: Saved to flash at F4, Count 394, Bytes 4096`
`00:00:20 TYA: RX Packet: "55aa03070005010100010112"`
`00:00:20 TYA: RX Device-1 --> MCU State: On Current State:Off`
`00:00:20 SRC: Switch`
`00:00:20 RSL: stat/GarageRechts/RESULT = {"POWER":"ON"}`
`00:00:20 RSL: stat/GarageRechts/POWER = ON`
So obviously switch hast DpID 1 and can be controlled already with actual software.

Closing the "door is closed" contact at runtime 01:01:34 (in fact it is a magnetic switch on a long cable) gives following output:
`00:01:34 TYA: RX Packet: "55aa03070005650100010075"`
`00:01:34 TYA: RX Device-101 --> MCU State: Off Current State:Off`
`00:01:34 TYA: RX Packet: "55aa03070005010100010011"`
`00:01:34 TYA: RX Device-1 --> MCU State: Off Current State:On`
`00:01:34 SRC: Switch`
`00:01:34 RSL: stat/GarageRechts/RESULT = {"POWER":"OFF"}`
`00:01:34 RSL: stat/GarageRechts/POWER = OFF`
`00:01:34 CFG: Saved to flash at FA, Count 396, Bytes 4096`
`00:01:34 TYA: Send "55aa00000000ff"`
`00:01:34 TYA: RX Packet: "55aa030000010104"`
`00:01:34 TYA: Heartbeat`
`00:01:50 TYA: RX Packet: "55aa03070005650100010176"`
`00:01:50 TYA: RX Device-101 --> MCU State: On Current State:Off`
`00:01:50 SRC: Switch`
`00:01:50 RSL: stat/GarageRechts/RESULT = {"POWER":"ON"}`
`00:01:50 RSL: stat/GarageRechts/POWER = ON`
`00:01:50 TYA: RX Packet: "55aa03070005010100010112"`
`00:01:50 TYA: RX Device-1 --> MCU State: On Current State:On`
`00:01:50 TYA: Send "55aa00000000ff"`
`00:01:50 TYA: RX Packet: "55aa030000010104"`
`00:01:50 TYA: Heartbeat`
`00:01:50 CFG: Saved to flash at F9, Count 397, Bytes 4096`
At 00:01:50 I removed the magnet and switch was reset.
So this switch seems to have DpID 101 (hex 0x65) and cannot be controlled neither queried by actual software. I do not have the option to set a switch's ID to 101.

When I query the device initialization status `55 aa 00 08 00 00 07` a device with ID 7 responds as well. Dunno what it is for, could imagine that it is some kind of LED status.
`00:04:40 CMD: SerialSend5  55 aa 00 08 00 00 07`
`00:04:40 RSL: stat/GarageRechts/RESULT = {"SerialSend":"Done"}`
`00:04:40 TYA: RX Packet: "55aa03070005010100010112"`
`00:04:40 TYA: RX Device-1 --> MCU State: On Current State:On`
`00:04:40 TYA: RX Packet: "55aa0307000807020004000000001e"`
`00:04:40 TYA: RX Unknown ID=7`
`00:04:40 TYA: RX Packet: "55aa03070005650100010176"`
`00:04:40 TYA: RX Device-101 --> MCU State: On Current State:Off`

So my desire is the possibility to configure ID's for the tuya switch(es), just like `SetOption 44` for the PowerID - then I could integrate this devices to my home control (OH2).

**Comment by Jason2866** [comment]
@shantur  Tuya;-) Can you take a look?

**Comment by shantur** [comment]
This was discussed in Discord chat.
Currently this isn't supported. It needs to be implemented

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by shantur** [comment]
I am working on a configurable implementation for Tuya mcu devices. 
Please re-open this to track the requirement.

**Comment by ascillato2** [comment]
Reopened as requested. Thanks.

**Comment by shantur** [comment]
Fixed in #6353

**Comment by juanjux** [comment]
For the record, I managed to flash this over the air with the [kueblc tuya convert fork] https://github.com/kueblc/tuya-convert (you need to switch to the `new-api` branch).

@riogrande75 whats settings are you using in the `Configure Module` and `Configure Template` of the device's config?

**Comment by riogrande75** [comment]
TuyaMCU (54). No Template, I used this settings to get stuff on my MQTT:
`TuyaMcu 41,1
TuyaMcu 2,101
SwitchTopic 0
Rule1 on switch2#state do publish stat/GarageLinks/sensor %value% endon
Rule1 on
Switchmode2 2`

**Comment by juanjux** [comment]
Thank you @riogrande75, this worked for me except every couple seconds it would lower the `dimmer` value until it went to 0 and the switch turned on, starting again from 100. Curiously I was able to solve it using the `fade on` console command, which very WTFishly stopped the fading.

**Comment by JHurk** [comment]
Am trying to get the Wofea Smart Garage Controller to work with Tasmota but with no luck.
The sensor doesn't seem to work and as soon as I toggle the button (on to off) it will return to on within seconds. Disconnection the magnetic door sensor will trigger the led light on the controller (it will start flashing red/blue fast) but this does nothing in Tasmota.

Could you please provide me with your settings so I can copy them to my controller?
I have tried the following steps:
- Module type: TuyaMCA (54)
- No Template set
- MQTT and Domoticz settings are correct (Domoticz only IDX 1 set to 49 which is the correct number and works from Domoticz)
- In console I entered the following commands, one after each other (and also tried all together in one time).
TuyaMcu 41,1
TuyaMcu 2,101
SwitchTopic 0
Rule1 on switch2#state do publish stat/GarageLinks/sensor %value% endon
Rule1 on
Switchmode2 2
SetOption65 1
fade on (this gives a result 'Command unknown').

Note: the controller is not yet connected to the garage doorcontroller which is located in my garage. So the black and red wires are not connected to anything. Could this be the problem? I tried to find out what would happen if I connect them as soon as I toggle the button, but connecting them doesn't make the switching between on-off go away.

**Comment by JHurk** [comment]
Update: I managed to get the Wofea Garage Door Controller working, at least half of it functions are working; opening and closing. 
The problem is with the reed (magnetic sensor). It is connected at the moment so the command in console is always the same:
4:50:50 MQT: tele/sonoff/RESULT = {"TuyaMcuReceived":"55AA030000010104"}

I do not have anywhere I can see the reed-status (connected or disconnected) and would not know how to get this to work. As soon as I disconnect the reed after I push the button and the door opens (the reed would then disconnect if it would be attached to the door, so I simulate this by disconnecting it manually) the door stops after a few seconds and after a few seconds the door closes. This continues until I connect the reed again.
How can I separate the reed and door button? I only want the reed to give me the door status (open/closed; disconnected/connected) and only want the button to act as a opener.

**Comment by meingraham** [comment]
@shantur ⬆️

**Comment by HABuild** [comment]
@JHurk 
This is what I use.
SwitchMode":[4,1,0,0,0,0,0,0]
{"Rule1":"Open","Once":"Open","StopOnError":"Open","Free":382,"Rules":"on switch2#state=1 do publish2 stat/SW_Garage/POWER2 Open endon on switch2#state=0 do publish2 stat/SW_Garage/POWER2 Closed endon"}

TYA: fnId=11 is set for dpId=1
TYA: fnId=2 is set for dpId=101
I have the LED off, but it could be ledlink.

I have interlock 1
I also have switch debounce, you shouldn't need this. I use a different reed switch, but I mounted it the wrong way. so I triggers twice as it slides open. 

in HA switch config I have

````
switch:
# tasmota setup, module 54, switchmode1 4, switchmode2 1, switchdebounce 1000(stops reed switch flicker), interlock 1 
  # rule1 on switch2#state=1 do publish2 stat/SW_Garage/POWER2 Open endon on switch2#state=0 do publish2 stat/SW_Garage/POWER2 Closed endon
  # publish2 in tasmota is rule to publish retained msg
  - platform: mqtt                              
    name: "Garage Door"
    state_topic: "stat/SW_Garage/POWER2"
    command_topic: "cmnd/SW_Garage/POWER1"
    availability_topic: "tele/SW_Garage/LWT"
    qos: 1
    state_on: "Open"
    state_off: "Closed"
    payload_on: "1"
    payload_off: "0"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false 
````

this is the card I use. 

````
entity: switch.garage_door
icon: 'mdi:garage'
lock:
  enabled: true
  unlock: tap
show_state: false
state:
  - color: 'rgb(255, 0, 0)'
    icon: 'mdi:garage-open'
    name: Garage Open
    styles:
      card:
        - animation: blink 2s linear infinite
    value: 'on'
  - color: 'rgb(0, 205, 0)'
    icon: 'mdi:garage'
    name: Garage Closed
    value: 'off'
  - color: 'rgb(255, 0, 0)'
    icon: 'mdi:garage-alert'
    name: Garage Offline
    spin: true
    value: unavailable
tap_action:
  action: call-service
  service: switch.turn_on
  service_data:
    entity_id: switch.garage_door
type: 'custom:button-card'
````
